<a href="https://colab.research.google.com/github/gnaneswar-18/preprocessing-4/blob/main/lab_2(multidimension_covarAndcorrelation).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
M = 5
N = 10
matrix = np.random.rand(M, N)

transposed_matrix = matrix.T
cov_matrix = np.cov(transposed_matrix, rowvar=False)
corr_matrix = np.corrcoef(transposed_matrix, rowvar=False)
print("Original Matrix (MxN):\n", matrix)
print("\nCovariance Matrix (MxM):\n", cov_matrix)
print("\nCorrelation Matrix (MxM):\n", corr_matrix)



Original Matrix (MxN):
 [[0.17974185 0.52386271 0.43573619 0.15530221 0.60772011 0.27849535
  0.51061789 0.85746491 0.59001441 0.48126627]
 [0.60482681 0.4453397  0.37644581 0.98347621 0.64555495 0.85117089
  0.38386513 0.47919114 0.59405286 0.00180117]
 [0.48239571 0.267064   0.11319441 0.24731297 0.37802868 0.0799413
  0.80357628 0.35652463 0.94345237 0.31314427]
 [0.81714586 0.42741353 0.40460207 0.74311458 0.32228853 0.50084241
  0.07140113 0.88284538 0.31822796 0.68419188]
 [0.35105721 0.11229607 0.60729092 0.75757044 0.72334041 0.74300157
  0.50687245 0.62518417 0.3822083  0.0486514 ]]

Covariance Matrix (MxM):
 [[ 0.04540815 -0.0258532   0.01652623 -0.00903062 -0.00552629]
 [-0.0258532   0.07389904 -0.00989914  0.00751379  0.05003192]
 [ 0.01652623 -0.00989914  0.07784187 -0.03049765 -0.01569038]
 [-0.00903062  0.00751379 -0.03049765  0.06665691 -0.00227628]
 [-0.00552629  0.05003192 -0.01569038 -0.00227628  0.0656178 ]]

Correlation Matrix (MxM):
 [[ 1.         -0.44630109  0.2